Jupyter.local.server.location.string={1}의 {0}
Jupyter.notebook.open.project.processor.name=작업공간 외부에서 파일을 열 때 디렉터리를 연결 안 함
Jupyter.remote.verify.url.empty=Jupyter URL이 공백일 수 없습니다
Jupyter.remote.verify.url.malformed=형태가 잘못된 URL입니다. http\://my.jupyter.org\:8888과 같은 형태의 Jupyter URL을 입력하세요
action.ReloadRemoteFileAction.description=서버에서 최신 변경 내용을 다시 로드합니다
action.ReloadRemoteFileAction.text=서버에서 다시 로드…
group.CellMenu.text=셀
group.KernelMenu.text=커널
notification.group.jupyter=Jupyter notebook
